export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const USERLIST_SUCCESS = "USERLIST_SUCCESS";
export const USERLIST_ERROR = "USERLIST_ERROR";
export const USERLIST_REQUEST = "USERLIST_REQUEST";

export const CHATLIST_SUCCESS = "CHATLIST_SUCCESS";
export const CHATLIST_ERROR = "CHATLIST_ERROR";
export const CHATLIST_REQUEST = "CHATLIST_REQUEST";

export const USERRECEIVERLIST_SUCCESS = "USERRECEIVERLIST_SUCCESS";
export const USERRECEIVERLIST_ERROR = "USERRECEIVERLIST_ERROR";
export const USERRECEIVERLIST_REQUEST = "USERRECEIVERLIST_REQUEST";

export const USERSEARCHLIST_SUCCESS = "USERSEARCHLIST_SUCCESS";
export const USERSEARCHLIST_ERROR = "USERSEARCHLIST_ERROR";
export const USERSEARCHLIST_REQUEST = "USERSEARCHLIST_REQUEST";