export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const USERLIST_SUCCESS = "USERLIST_SUCCESS";
export const USERLIST_ERROR = "USERLIST_ERROR";
export const USERLIST_REQUEST = "USERLIST_REQUEST";

export const CHATLIST_SUCCESS = "CHATLIST_SUCCESS";
export const CHATLIST_ERROR = "CHATLIST_ERROR";
export const CHATLIST_REQUEST = "CHATLIST_REQUEST";

export const USERRECEIVERLIST_SUCCESS = "USERRECEIVERLIST_SUCCESS";
export const USERRECEIVERLIST_ERROR = "USERRECEIVERLIST_ERROR";
export const USERRECEIVERLIST_REQUEST = "USERRECEIVERLIST_REQUEST";

export const USER_PROFILE_LIST_SUCCESS = "USER_PROFILE_LIST_SUCCESS";
export const USER_PROFILE_LIST_ERROR = "USER_PROFILE_LIST_ERROR";
export const USER_PROFILE_LIST_REQUEST = "USER_PROFILE_LIST_REQUEST";

export const UPDATE_USER_PROFILE_LIST_SUCCESS =
  "UPDATE_USER_PROFILE_LIST_SUCCESS";
export const UPDATE_USER_PROFILE_LIST_ERROR = "UPDATE_USER_PROFILE_LIST_ERROR";
export const UPDATE_USER_PROFILE_LIST_REQUEST =
  "UPDATE_USER_PROFILE_LIST_REQUEST";

export const USER_STORIES_LIST_SUCCESS = "USER_STORIES_LIST_SUCCESS";
export const USER_STORIES_LIST_ERROR = "USER_STORIES_LIST_ERROR";
export const USER_STORIES_LIST_REQUEST = "USER_STORIES_LIST_REQUEST";

export const ADD_STORIES_LIST_SUCCESS = "ADD_STORIES_LIST_SUCCESS";
export const ADD_STORIES_LIST_ERROR = "ADD_STORIES_LIST_ERROR";
export const ADD_STORIES_LIST_REQUEST = "ADD_STORIES_LIST_REQUEST";

export const USER_VIEW_STORIES_LIST_SUCCESS = "USER_VIEW_STORIES_LIST_SUCCESS";
export const USER_VIEW_STORIES_LIST_ERROR = "USER_VIEW_STORIES_LIST_ERROR";
export const USER_VIEW_STORIES_LIST_REQUEST = "USER_VIEW_STORIES_LIST_REQUEST";

export const USER_SELF_STORIES_LIST_ERROR = "USER_SELF_STORIES_LIST_ERROR";
export const USER_SELF_STORIES_LIST_SUCCESS = "USER_SELF_STORIES_LIST_SUCCESS";
export const USER_SELF_STORIES_LIST_REQUEST = "USER_SELF_STORIES_LIST_REQUEST";

export const USER_GET_STORIES_LIST_ERROR = "USER_GET_STORIES_LIST_ERROR";
export const USER_GET_STORIES_LIST_SUCCESS = "USER_GET_STORIES_LIST_SUCCESS";
export const USER_GET_STORIES_LIST_REQUEST = "USER_GET_STORIES_LIST_REQUEST";
